### ISSUE TITLE
QueryColumn 生成的字段, 能否带上泛型

### ISSUE THREAD

**Issue by emacsist** [mybatis-flex/mybatis-flex#105]
比如示例的 `ACCOUNT.ID.eq()` , 如果是 Long 类型, 希望 eq 后面的参数也是 Long 类型的. 而不是 Object , 这样可以检查一下.

**Comment by yangfuhai** [comment]
以后估计也不会添加泛型这支持的。

理由是： Account.id 的类型，如果是 Long, 传入 int  long  bigInterger 等等都是没问题的。 而且，在 flex 中，还有 where id = (select ..) 等子查询的情况，flex 并不是单表查询二设计的。
