### ISSUE TITLE
与mapstruct冲突问题

### ISSUE THREAD

**Issue by timeroar** [mybatis-flex/mybatis-flex#107]
当我在mapstruct引入 mybatis-flex相关的类的时候,就会导致APT引入的类编译不通过
![18_9~WPE%4LV~ABX62_}8 4](https://github.com/mybatis-flex/mybatis-flex/assets/37179977/ac1d4668-63e0-4ab1-841b-931164a9fbba)

**Comment by yangfuhai** [comment]
查看文档：https://mybatis-flex.com/zh/others/apt.html#%E5%92%8C-lombok%E3%80%81mapstruct-%E6%95%B4%E5%90%88
