### ISSUE TITLE
连表查询，传参一直传不进去

### ISSUE THREAD

**Issue by 18696232390** [mybatis-flex/mybatis-flex#113]
```java
@GetMapping("/test")
    public Object test(){
        QueryWrapper where = QueryWrapper.create().select()
                .from(TClassTableDef.T_CLASS)
                .innerJoin(TUserTableDef.T_USER)
                .on(TClassTableDef.T_CLASS.USER_ID.eq(TUserTableDef.T_USER.ID))
                .where(TClassTableDef.T_CLASS.USER_ID.eq("1"));

        return classFlexMapper.selectListByQuery(where);
    }
```

```java

### SQL: SELECT * FROM `t_class` INNER JOIN `t_user` ON `t_class`.`user_id` = `t_user`.`id` WHERE `t_class`.`user_id` = ?
### Cause: java.sql.SQLException: No value specified for parameter 1
; bad SQL grammar []; nested exception is java.sql.SQLException: No value specified for parameter 1] with root cause

java.sql.SQLException: No value specified for parameter 1

```

**Comment by 18696232390** [comment]
明明传了 eq("1") 可是还是报错  No value specified for parameter 1

**Comment by yangfuhai** [comment]
应该是 Mybatis-flex 没有正常启动，请查看一下您的项目问题是否有这些常见问题：https://mybatis-flex.com/zh/faq.html

**Comment by loong0306** [comment]
![image](https://github.com/mybatis-flex/mybatis-flex/assets/12693644/11e3b5da-295d-4c5f-9870-3fbf9d6454b6)
应该没什么问题

**Comment by Suomm** [comment]
排查问题：https://mybatis-flex.com/zh/faq.html#mybatis-flex-%E6%B2%A1%E6%9C%89%E5%90%AF%E5%8A%A8%E6%88%96%E8%80%85%E5%90%AF%E5%8A%A8%E5%87%BA%E9%94%99%E6%80%8E%E4%B9%88%E5%8A%9E

**Comment by hojit** [comment]
<img width="866" alt="image" src="https://github.com/mybatis-flex/mybatis-flex/assets/24590630/ad2c023a-b8e3-4b1d-90d3-0a996ae577fe">
一样的错误，1.5.5就不行，1.5.1可以
这样太不严谨了呀，单元测试可以通过吗？

**Comment by loong0306** [comment]
> <img alt="image" width="866" src="https://user-images.githubusercontent.com/24590630/257979183-ad2c023a-b8e3-4b1d-90d3-0a996ae577fe.png"> 一样的错误，1.5.5就不行，1.5.1可以 这样太不严谨了呀，单元测试可以通过吗？

![image](https://github.com/mybatis-flex/mybatis-flex/assets/12693644/5dcfccb4-ca8c-447a-8aef-f723f84a5515)
1.5.5的包，我这边没复现出来

**Comment by hojit** [comment]
> > <img alt="image" width="866" src="https://user-images.githubusercontent.com/24590630/257979183-ad2c023a-b8e3-4b1d-90d3-0a996ae577fe.png"> 一样的错误，1.5.5就不行，1.5.1可以 这样太不严谨了呀，单元测试可以通过吗？
> 
> ![image](https://user-images.githubusercontent.com/12693644/257985712-5dcfccb4-ca8c-447a-8aef-f723f84a5515.png) 1.5.5的包，我这边没复现出来

<img width="1086" alt="image" src="https://github.com/mybatis-flex/mybatis-flex/assets/24590630/55b12a2d-f990-4c34-94fe-79caa1561d3b">
<img width="1053" alt="image" src="https://github.com/mybatis-flex/mybatis-flex/assets/24590630/682a0814-5f99-4a77-8407-15a7ff9da965">
不好意思，为之前的言行道歉
我在使用kotlin的时候，编译无法通过，报错
但是用Java的话，可以通过，得到正确结果
