### ISSUE TITLE
用的有点懵逼了

### ISSUE THREAD

**Issue by wanxiaochao** [mybatis-flex/mybatis-flex#126]
QueryWrapper query = hisMedItemService.query();
        List<HisMedItem> list = hisMedItemService
                .list(query.where(HisMedItemTableDef.HIS_MED_ITEM.E_INVOICE_ID.eq("id")));
        System.out.println(1);
这段代码执行就会报错   索引中丢失  IN 或 OUT 参数:: 1
用的oracle数据库 求个大佬指点一下

其次很纳闷文档中的ACCOUNT那个是怎么生成的可以直接用，我这就是这个HisMedItemTableDef。

**Comment by yangfuhai** [comment]
这个问题应该是 mybatis-flex 没有加载，没有正常启动。 请参考一下您的项目是否有这些常见问题：https://mybatis-flex.com/zh/faq.html

**Comment by wanxiaochao** [comment]
谢谢！解决了！
