### ISSUE TITLE
实体类 字段配置注解 typeHandler @Column(jdbcType = JdbcType.NVARCHAR,typeHandler = Fastjson2TypeHandler.class)  查询报错

### ISSUE THREAD

**Issue by 999-wq** [mybatis-flex/mybatis-flex#128]
![image](https://github.com/mybatis-flex/mybatis-flex/assets/68933010/4d1db2d0-cbba-4939-881b-1974e060975e)

**Comment by yangfuhai** [comment]
具体是什么错误呢？

**Comment by 999-wq** [comment]
> 

不好意思我没说清楚，就是在使用IService的list接口的时候 报错；我尝试着看了下代码 发现在 TableInfoFactory 的 321行  Configuration configuration = FlexGlobalConfig.getDefaultConfig().getConfiguration();这一段 获取的 configuration  为null；导致下一行 configuration.getTypeHandlerRegistry(); 报空指针错误；您可以看下我上面的截图

**Comment by yangfuhai** [comment]
这个能否远程看一下？

**Comment by yangfuhai** [comment]
> 这个能否远程看一下？

我这边本地验证是没有问题的

**Comment by 999-wq** [comment]
> > 这个能否远程看一下？
> 
> 我这边本地验证是没有问题的

这个 怎么远程 ？ 向日葵还是todesk？

**Comment by yangfuhai** [comment]
> > > 这个能否远程看一下？
> > 
> > 
> > 我这边本地验证是没有问题的
> 
> 这个 怎么远程 ？ 向日葵还是todesk？

添加 QQ 群：https://github.com/mybatis-flex/mybatis-flex/issues/128  联系一下我呗（群主😊）

**Comment by 999-wq** [comment]
是因为和pagehelper冲突了，感谢大佬的帮助
