### ISSUE TITLE
找不到 QueryColumnBehavior类

### ISSUE THREAD

**Issue by CHExN** [mybatis-flex/mybatis-flex#129]
在官网中得知 QueryColumnBehavior 配置在v1.5.6版本中，但在此版本中无法找到 QueryColumnBehavior 类

<img width="711" alt="image" src="https://github.com/mybatis-flex/mybatis-flex/assets/51228641/55d68c8f-590e-4364-8d0d-deebdedd841c">

<img width="1000" alt="image" src="https://github.com/mybatis-flex/mybatis-flex/assets/51228641/5edd8100-c21b-4853-9c69-fc6c484d3b31">

**Comment by yangfuhai** [comment]
QueryColumnBehavior 这个在 1.5.7 中提供，已经提交代码了，但是还没发版，文档的版本标识错误了。

**Comment by yangfuhai** [comment]
文档已更新，这个在下个版本提供。
