### ISSUE TITLE
多数据源是否提供统一的MapperScan扫包？文档中提供方法每个mapper都要写@UseDataSource

### ISSUE THREAD

**Issue by bigmzc** [mybatis-flex/mybatis-flex#131]
https://mybatis-flex.com/zh/core/multi-datasource.html 中罗列了四个用法，并没有扫包方法

**Comment by kthirty** [comment]
MapperScan是Mybatis原生的扫描，Mybatis-Flex只是增强，原始的MapperScan还是之前的用法没变。示例见：[mybatis-flex-test](https://gitee.com/Suomm/mybatis-flex-test/blob/master/src/main/java/com/mybatisflex/test/MybatisFlexTestApplication.java)

**Comment by kthirty** [comment]
> https://mybatis-flex.com/zh/core/multi-datasource.html 中罗列了四个用法，并没有扫包方法

**Comment by yangfuhai** [comment]
在 spring 下，可以直接在 Controller 或者 service 里使用 @UseDataSource 。
