### ISSUE TITLE
queryWrapper.select() 目前支持distinct 吗？ 

### ISSUE THREAD

**Issue by cuidq** [mybatis-flex/mybatis-flex#133]
queryWrapper.select() 目前支持distinct 吗？ 在api 中没有看到对应的用法，不过暂时是可以用groupBy 解决这个问题

**Comment by CHExN** [comment]
<img width="843" alt="image" src="https://github.com/mybatis-flex/mybatis-flex/assets/51228641/b5316b0d-e149-4c9e-962b-2a8566c162db">
https://mybatis-flex.com/zh/base/querywrapper.html

**Comment by cuidq** [comment]
谢谢，已经解决我的问题

**Comment by cuidq** [comment]
请问一下select 支持GROUP_CONCAT 吗？
