### ISSUE TITLE
执行update时SQL拼接错误

### ISSUE THREAD

**Issue by darrenxyue** [mybatis-flex/mybatis-flex#137]
表里面有version字段，但是并未设置为乐观锁，然后执行update方法的时候SQL拼接有问题
SpringBoot: 2.2.8
Mybatis-Flex: 1.5.7
业务代码：
![image](https://github.com/mybatis-flex/mybatis-flex/assets/28799116/7ef290e7-80e0-4938-92dc-824f10b9bff0)

字段定义：
![image](https://github.com/mybatis-flex/mybatis-flex/assets/28799116/bb24986d-4e79-4a31-9d4f-118d1660def7)

错误信息：

**Comment by darrenxyue** [comment]
我这张表里面的version是需要version字段，但不是用来作为乐观锁，我理解@Column里面的version值默认为false的话这个字段是不会被识别为乐观锁字段的

**Comment by yangfuhai** [comment]
这个是由于 mybatis-flex 默认设置了全局的乐观锁字段了，下个版本修复这个问题。

**Comment by darrenxyue** [comment]
好勒，赞👍
