### ISSUE TITLE
queryChain 查询时，参数能够支持区分大小写

### ISSUE THREAD

**Issue by Hliyidexiaoguaishou** [mybatis-flex/mybatis-flex#143]
![image](https://github.com/mybatis-flex/mybatis-flex/assets/38741905/7ecaa6cc-8626-4fdc-acfa-d99714d125da)
![image](https://github.com/mybatis-flex/mybatis-flex/assets/38741905/2f6c1faa-f258-4d4d-bd27-40c429cd2ce9)
上面参数如果不区分大小写，传入COkAAAHbnxhECefw 会连 COkAAAHBnXhECefw 的记录一起查询出来

**Comment by yangfuhai** [comment]
这个是数据库的问题，而非 mybatis-flex 的问题。
