### ISSUE TITLE
orcale兼容ORA-00911: 无效字符

### ISSUE THREAD

**Issue by ijry** [mybatis-flex/mybatis-flex#144]
SELECT `id`, `project_id`, `item_id` FROM `TEST_ITEM` 
生成的语句带·这个符号就报错  SELECT id, project_id, item_id FROM TEST_ITEM ，拷贝出sql去掉所有 `就能执行SQL。

**Comment by yangfuhai** [comment]
大概率是 mybatis-flex 没有被正常启动，请查看一下您的项目是否有这些常见问题：https://mybatis-flex.com/zh/faq.html

**Comment by yangfuhai** [comment]
新版本验证没有问题。
