### ISSUE TITLE
自动生成基础的Mapper

### ISSUE THREAD

**Issue by game4dream** [mybatis-flex/mybatis-flex#145]
自动生成TableRef的同时，可否也自动生成一个基础的BaseMapper？
`
@Table("demo")
public class Demo {

  @Id(keyType = KeyType.Auto)
  int id;

  String name;

  String remark;

}

`

`
public interface DemoMapper extends BaseMapper<Demo> {

}

`

**Comment by CHExN** [comment]
<img width="1244" alt="image" src="https://github.com/mybatis-flex/mybatis-flex/assets/51228641/3e4b00ac-ac13-440c-bdaf-9d1cdf7a8f61">

https://mybatis-flex.com/zh/others/apt.html

**Comment by yangfuhai** [comment]
已经支持。
