### ISSUE TITLE
如何更新时忽略租户条件

### ISSUE THREAD

**Issue by rickyhuangdev** [mybatis-flex/mybatis-flex#149]
看了文档没有详细的说明
` public boolean updateCarrierCharges(CarrierChargesDTO carrierCharges) throws ServiceException {
        try {
            CarrierCharges charges = createCarrierCharges(carrierCharges);
            if (getById(charges.getId()) == null) {
                throw new ServiceException("请求更新资源不存在");
            }
//            TenantManager.withoutTenantCondition((CarrierChargesMapper)->{
//                try {
//                    TenantManager.ignoreTenantCondition();
//                    //此处操作的数据不会带有 tenant_id 的条件
//                    carrierChargesMapper.update(charges);
//                } finally {
//                    TenantManager.restoreTenantCondition();
//                }
//
//            });
            System.out.println(charges.getOrgProfileId());
            boolean saved = false;
            try {
                TenantManager.ignoreTenantCondition();
                saved = updateById(charges);
            } finally {
                TenantManager.restoreTenantCondition();
            }

            carrierChargeDetailService.updateChargeDetail(carrierCharges.getChargeDetail(), charges.getId());

            log.info("Carrier charges updated with id: {}", charges.getId());
            return saved;
        } catch (Exception e) {
            log.error("Error updating carrier charges: {}", e.getMessage(), e);
            throw new ServiceException("更新Carrier费用失败费用失败");
        }
    }`

  `
    @Configuration
public class MyBatisFlexConfiguration implements MyBatisFlexCustomizer {

    private static final Logger logger = LoggerFactory.getLogger("mybatis-flex-sql");

    public MyBatisFlexConfiguration() {
        AuditManager.setAuditEnable(true);
        AuditManager.setMessageCollector(auditMessage -> logger.info("{},{} ms", auditMessage.getFullSql(), auditMessage.getElapsedTime()));
        TenantManager.setTenantFactory(() -> new Object[]{});
        QueryColumnBehavior.setIgnoreFunction(new Predicate<Object>() {
            @Override
            public boolean test(Object o) {
                return "".equals(o);
            }
        });
        QueryColumnBehavior.setSmartConvertInToEquals(true);

        FlexGlobalConfig.KeyConfig keyConfig = new FlexGlobalConfig.KeyConfig();
        keyConfig.setKeyType(KeyType.Generator);
        keyConfig.setValue(KeyGenerators.flexId);
        keyConfig.setBefore(true);

        FlexGlobalConfig.getDefaultConfig().setKeyConfig(keyConfig);
    }

    @Override
    public void customize(FlexGlobalConfig flexGlobalConfig) {
        FlexGlobalConfig.getDefaultConfig().setTenantColumn(Constants.TENANT_ID);
    }

}
  `

**Comment by yangfuhai** [comment]
看文档：https://mybatis-flex.com/zh/core/multi-tenancy.html#%E5%BF%BD%E7%95%A5%E7%A7%9F%E6%88%B7%E6%9D%A1%E4%BB%B6

**Comment by GabbyMrH** [comment]
Mybatis flex 1.10.2的一个新问题：如果更新时平台作为管理方想手动修改租户ID，无法更改。
> 看文档：https://mybatis-flex.com/zh/core/multi-tenancy.html#%E5%BF%BD%E7%95%A5%E7%A7%9F%E6%88%B7%E6%9D%A1%E4%BB%B6
