### ISSUE TITLE
insertBatch 批量插入数据时无法使用数据库默认值

### ISSUE THREAD

**Issue by llll1004** [mybatis-flex/mybatis-flex#153]
若有默认值字段为 null，则生成的 SQL 也会被设置为 null
如：INSERT INTO `table_name`(`a`, `b`, `c`) VALUES (a1, b1, null), (a2, b2, null)
希望可以和 insert 一样可以忽略 null 字段

**Comment by yangfuhai** [comment]
看视频教程 https://www.bilibili.com/video/BV1PV4y1Y73a/
