### ISSUE TITLE
如何快速从mybatis-plus迁移到mybatis-flex？

### ISSUE THREAD

**Issue by mostcool** [mybatis-flex/mybatis-flex#159]
如题，有相关指导文档或快速方法吗？
作者是否可以考虑下这种迁移？

**Comment by yangfuhai** [comment]
从 v1.7.2 开始，MyBatis-Flex 已经支持 MyBatis-Plus 兼容 api，参考：https://mybatis-flex.com/zh/base/querywrapper.html#mybatis-plus-%E5%85%BC%E5%AE%B9-api

**Comment by wangran99** [comment]
能够跟plus共存吗？flex获取getmapper（）总是拿到plus的mapper
