### ISSUE TITLE
查询时传入条件为null时会被忽略查询

### ISSUE THREAD

**Issue by zhangchaolunha** [mybatis-flex/mybatis-flex#160]
查看过文档看原因时因为QueryColumnBehavior 的默认设置QueryColumnBehavior.setIgnoreFunction(o -> o == null）就会忽略，但是在业务中涉及到需要传入null的情况。。目前使用修改setIgnoreFunction的方式仍然会报错提示
![image](https://github.com/mybatis-flex/mybatis-flex/assets/63902798/8aa168e6-4266-4ad6-b7cb-d27f8d3f9086)
目前是否有方法解决？

**Comment by xingfudeshi** [comment]
如果是数据库中查询'null',可以作为字符串传

**Comment by zhangchaolunha** [comment]
不能不处理不忽略像mp一样嘛？业务需要不能忽略处理。。。有时候就需要库里的这个值通过传入=null查询不到数据。

**Comment by yangfuhai** [comment]
> 不能不处理不忽略像mp一样嘛？业务需要不能忽略处理。。。有时候就需要库里的这个值通过传入=null查询不到数据。

可以的，参考 QueryColumnBehavior，文档：https://mybatis-flex.com/zh/base/querywrapper.html#querycolumnbehavior
