### ISSUE TITLE
加减乘除不支持处理SelectQueryColumn

### ISSUE THREAD

**Issue by arkerwu** [mybatis-flex/mybatis-flex#166]
QueryWrapper queryWrapper = QueryWrapper.create()
            .select(count().add(**new SelectQueryColumn(select(count()).from(ARTICLE)))**)
            .from(ARTICLE);
运行后:
SELECT COUNT(*) + `tb_article`.**null** FROM `tb_article` WHERE `account_id` = ? LIMIT 0, 10

**Comment by yangfuhai** [comment]
参考文档：https://mybatis-flex.com/zh/base/querywrapper.html#select-%E5%88%97%E8%AE%A1%E7%AE%97
