### ISSUE TITLE
请问如何对  where 的条件添加函数?  文档上好像没找到.

### ISSUE THREAD

**Issue by kyochou** [mybatis-flex/mybatis-flex#168]
比如这种: 
select * from player_info where date(created_at) = '2023-09-16'
怎么添加 date 函数到 created_at 字段上?

**Comment by zundaren** [comment]
用拼接的方式where("date(created_at) = 'xxx'")

**Comment by kyochou** [comment]
谢谢回答. 感觉这样就硬编码了. 对重构很不友好. 
感觉这又是个 kpi  项目啊. issue 基本没人打理的.

**Comment by kyochou** [comment]
好的. 是我冒犯了.  我还以为大部分开源项目都是以 github 为主.
总体来说项目还是挺不错. 用起来很舒服.
