### ISSUE TITLE
[使用问题]: informix sql 語法錯誤

### ISSUE THREAD

**Issue by vt167098** [mybatis-flex/mybatis-flex#179]
### 这个问题是否已经存在：

- [x] 我确定已经把 MyBatis-Flex 升级到最新版本 v1.6.8，并已搜索过现有的问题 (https://gitee.com/mybatis-flex/mybatis-flex/issues)

### 使用时遇到的问题描述：

連結資料庫: informix
環境: spring boot 3 + druid 1.2.19
報錯狀況: `### Error querying database.  Cause: java.sql.SQLException: An illegal character has been found in the statement.
### Cause: java.sql.SQLException: An illegal character has been found in the statement.
; uncategorized SQLException; SQL state [IX000]; error code [-202]; An illegal character has been found in the statement.] with root cause
`
我查出原因是因為組出的sql statement 的column 與 table都有用"`"括起來所造成的錯誤, 請問要如何取消"`"這括起來的動作.

正常的sql應該是這樣 
SELECT tab_name, col_name, col_value, col_desc, end_mark, create_id, create_date, update_id, update_date, order FROM cntm110

謝謝.

### 截图或视频：

[在这里上传图片]

### 关联版本：

1.6.8

**Comment by yangfuhai** [comment]
出现这个错误的问题原因，可能是因为 mybatis-flex 没有成功启动导致的。请查看一下您的项目是否有这些常见问题：https://mybatis-flex.com/zh/faq.html#mybatis-flex-%E6%B2%A1%E6%9C%89%E5%90%AF%E5%8A%A8%E6%88%96%E8%80%85%E5%90%AF%E5%8A%A8%E5%87%BA%E9%94%99%E6%80%8E%E4%B9%88%E5%8A%9E

**Comment by vt167098** [comment]
謝謝您, 我找到問題了.
