### ISSUE TITLE
独创的 FlexID 算法生成的数据库主键，在传回前端时，会导致精度不准确

### ISSUE THREAD

**Issue by hanyongcheng** [mybatis-flex/mybatis-flex#208]
前端使用的jquery发送的ajax请求，后端响应的id数据值为19998748185000191，ajax接收后，id的数据值变成了19998748185000190，能否考虑下缩短下id的位数
![image](https://github.com/mybatis-flex/mybatis-flex/assets/44747087/46439a14-254d-41d3-9325-6fc6257201a1)

**Comment by wanniwa** [comment]
这种一般是后端将Long类型传给前端时，统一转化成String可以解决，不可能要求数据库层面的框架缩小字段长度去解决的
