### ISSUE TITLE
基本功能bug---- in方法

### ISSUE THREAD

**Issue by niko349** [mybatis-flex/mybatis-flex#217]
pom版本：
```
 <dependency>
            <groupId>com.mybatis-flex</groupId>
            <artifactId>mybatis-flex-spring-boot-starter</artifactId>
            <version>1.7.3</version>
        </dependency>
```

![d63b1e20c94f2672dad0415e7632778](https://github.com/mybatis-flex/mybatis-flex/assets/123226670/b587dadb-161f-487a-88ad-db4ace2c743b)

理论上就算是空列表也不应该给我忽略掉，而是直接报错

**Comment by niko349** [comment]
> Mybatis-Flex会自动忽略null，这是设计如此，官网已经讲述比较清楚了，并非BUG。见QueryColumnBehavior章节。

我知道默认会忽视，可是这个方法后面是有条件进行控制的，有条件的情况下，不应该忽视呀

**Comment by luo-zhan** [comment]
> > Mybatis-Flex会自动忽略null，这是设计如此，官网已经讲述比较清楚了，并非BUG。见QueryColumnBehavior章节。
> 
> 我知道默认会忽略，可是这个方法后面是有条件进行控制的。有条件的情况下，不应该忽略呀

既然知道参数为null或空集合执行sql会报错，为啥还要这样设计，不应该自己判断吗in参数为空的逻辑吗，无非就是两种：忽略条件或者返回空结果集，flex默认是忽略条件，如果你的业务场景是后者，就在执行sql前做一次判断空集合，是的话就直接返回。flex这么设计没毛病的

**Comment by wanniwa** [comment]
应该还是报错好吧，orm算是最后的兜底的地方了，如果不报错，很可能有人业务代码没判空，一直也不报错，但是这个筛选自动消失了，又把所有数据查出来，业务可能能正常走，但是数据可能已经全乱了，想想都恐怖。

**Comment by yangfuhai** [comment]
这个问题在新版本里已修复。
