### ISSUE TITLE
springboot 3.2.0启动报错

### ISSUE THREAD

**Issue by lizhuoxuan** [mybatis-flex/mybatis-flex#218]
springboot 3.2.0
mybatis flex 1.7.4

**Comment by zev-223** [comment]
mybatis-spring 需要升级到3.0.3

**Comment by lcxw** [comment]
需要升级mybatis-spring的版本和mybatis的版本，另外需要注意，如果是通过`mybatis-flex-dependencies`bom文件管理的mybatis-flex依赖，mybatis-flex-parent中指定了`spring.version`参数的，可能会覆盖项目中的spring.version参数，导致引入的spring-data-jdbc，spring-framework等依赖版本是引入的5.x.x的版本，需要注意下，

**Comment by yangfuhai** [comment]
参考文档 https://mybatis-flex.com/zh/faq.html#springboot-3-2-%E9%A1%B9%E7%9B%AE-%E5%90%AF%E5%8A%A8%E6%8A%A5%E9%94%99-invalid-value-type-for-attribute-factorybeanobjecttype-java-lang-string
