### ISSUE TITLE
建议为 springboot 2.x 3.x发布不同的版本的 starter

### ISSUE THREAD

**Issue by victor-0807** [mybatis-flex/mybatis-flex#223]
springboot 不同版本差异还是比较大的，建议发布对应版本的 starter，比如针对 2.7.x ，3.2.x分别提供，版本好可以为 2.7-1.7.5,3.2-1.7.5，这样可以简化使用，不然还一通折腾

**Comment by yangfuhai** [comment]
这个确实可以考虑

**Comment by yangfuhai** [comment]
v1.7.7 已支持。
