### ISSUE TITLE
[建议&问题] Pagination分页查询功能不能支持根据条件进行分页查询或者查询所有数据？

### ISSUE THREAD

**Issue by jackson-som** [mybatis-flex/mybatis-flex#24]
问题：
- 使用该分页查询功能必须提供``Page``或者其他参数，但如果不想要分页查询就会抛出异常。

原因：
- 由于提供给前端的接口属于比较大众化，可根据条件去进行分页查询或者查询所有数据，但是后端处理会比较麻烦和困难。

---

这以前的写法，不管是使用Mapper.xml还是类似于MyBatis的Example，都是使用PageHelper来帮忙分页查询的。

``` java
public void startPage(Pagination pagination) {
   if (pagination != null) {
       if (pagination.getPageNumber() > 0) {
           PageHelper.startPage(pagination.getPageNumber(), pagination.getRowPerPage());
       }
   }
}

--- 分割线 ---

FilterUtil.startPage(filter.getPagination());

List<CategoryBean> list = customMapper.getCategoryByFilter(subFilter); // 使用了 Mapper.xml 处理查询

return Result.standardizedWithObject(list, Page.of(list)); // Page.of(list) 处理并且拿出分页数据，为了统一格式分页数据

```

---

这使用了MyBatis-Flex之后的写法，由于前面 ``QueryWrapper`` 写法非常方便，但必须使用 Page<T> 功能，而且不支持PageHelper分页查询。

``` java

QueryWrapper query = QueryWrapper.create()
     .and(category.type.eq(FilterUtil.search(subFilter.getType())))
     .and(category.name.like(FilterUtil.search(subFilter.getName())))
     .and(category.status.eq(FilterUtil.search(subFilter.getStatus())));

// filter.getPagination().page() 是 Page<T>
Page<Category> list = categoryMapper.paginate(filter.getPagination().page(), query);

// list.getRecords() 是为了统一化格式返回数据
// list 是会处理 Page<T> 的分页数据，这也是为了统一格式分页数据，避免参数名称不一样
return Result.standardizedWithObject(list.getRecords(), list);

```

这代码 ``categoryMapper.paginate(filter.getPagination().page(), query)`` 如果想要查询所有数据，不管是提供null值还是其他参数都会抛出异常，目前找不到解决方法。

希望能够支持按照条件分页查询或者查询所有，如果方便的话可以提供解决方案，不然只能使用旧方法了。

另外，项目都是使用较新版本的，不管是Spring Boot，PageHelper，还是Mybatis-Flex。

非常感谢。

**Comment by yangfuhai** [comment]
代码已提交，下个版本支持。另外，针对查询所有数据的场景，可以使用  selectAll() 方法。或者 selectListByQuery.

**Comment by gucg0307** [comment]
解决了吗？怎么解决的？

**Comment by jackson-som** [comment]
这问题很久了，如果我没记错的话，这问题已经解决了，因为下一个版本就解决了我的问题。但是目前MyBatis-Flex最新版本有没有改动我就不清楚了，不过多数是没改动没问题的，毕竟我看过源代码只是改一些东西判断值罢了就解决我的问题了。

> 解决了吗？怎么解决的？
