### ISSUE TITLE
[Feature] Using Testcontainers to do integration tests

### ISSUE THREAD

**Issue by Martin7-1** [mybatis-flex/mybatis-flex#246]
Hi! It seems that in `mybatis-flex` there are many tests need local MySQL deployment (such as `QueryChainTest` in `mybatis-flex-spring-boot-test`). I think we can use [Testcontainers](https://testcontainers.com/) to do these integration tests. Using `Testcontainers` will improve test quality and efficiency of test execution.

What do you think about it? I will PR for it if you think is ok. Waiting for you resposne!

**Comment by lcxw** [comment]
you can try it, pull request are welcome.⛳
