### ISSUE TITLE
IService 里面的exists方法，在sqlserver 下报错

### ISSUE THREAD

**Issue by font-C** [mybatis-flex/mybatis-flex#255]
版本：1.7.7

IService 里面的exists方法，在sqlserver 下报错

<img width="1278" alt="image" src="https://github.com/mybatis-flex/mybatis-flex/assets/131338252/47ac0997-056e-4e34-a05a-b2f76d6dfd38">
 

<img width="825" alt="image" src="https://github.com/mybatis-flex/mybatis-flex/assets/131338252/ed4901ef-9d97-4a45-b239-9f4d8633abaa">
该方法的selectOne 列没有配置别名，会导致在sqlserver下报错！

**Comment by yangfuhai** [comment]
已 merge.
