### ISSUE TITLE
严重问题：insertOrUpdate 没有作用，甚至无法插入

### ISSUE THREAD

**Issue by Lee3S** [mybatis-flex/mybatis-flex#260]
insertOrUpdateSelective(Obj)  插入0更新0
insertOrUpdate(Obj) 插入0更新0
insert(Obj) 插入1条

注：Obj是一条有主键的数据

怎么会发生这种情况？ 难道这条数据有主键就不进行插入了吗？ 不是根据主键来判断是否是更新还是插入吗？
很不解

**Comment by font-C** [comment]
![image](https://github.com/mybatis-flex/mybatis-flex/assets/131338252/b86dbbe2-eec1-4fb7-9674-60299980e9e3)

**Comment by Lee3S** [comment]
我的Obj中主键字段的值在数据库中是不存在的，理论上来说在使用insertOrUpdate的时候应该在数据库插入一条数据，但是并没有插入；是我哪里理解有出入吗？

**Comment by Lee3S** [comment]
> ![image](https://private-user-images.githubusercontent.com/131338252/296636944-b86dbbe2-eec1-4fb7-9674-60299980e9e3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUyODYxMjUsIm5iZiI6MTcwNTI4NTgyNSwicGF0aCI6Ii8xMzEzMzgyNTIvMjk2NjM2OTQ0LWI4NmRiYmUyLWVlYzEtNGZiNy05Njc0LTYwMjk5OTgwZTllMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDExNVQwMjMwMjVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zN2Y2ZDQ4NjRkOGQ1MTlmMmMyNDc1NmMwMmFjYTVlMWNhMjI1OTZlZmRmN2YzMmRiOGQzYzQ4ODg3NDUzMjQ4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Yxg-5pTrBhSvIS6dzwKMNTp7P-Z2Q4T9L5tb43qiXjQ)

我的Obj中主键字段的值在数据库中是不存在的，理论上来说在使用insertOrUpdate的时候应该在数据库插入一条数据，但是并没有插入；是我哪里理解有出入吗？

**Comment by font-C** [comment]
<img width="660" alt="image" src="https://github.com/mybatis-flex/mybatis-flex/assets/131338252/ae898e39-0aa4-40d6-b65e-4128f77a6889">

判断实体里面的主键是否有值，不是判断数据库中是否存在

**Comment by SWQXDBA** [comment]
用法有问题
文档写的很明白：是根据这个实体的主键有没有值来判断更新还是插入，而不是根据数据库中有没有这个主键值来判断更新还是插入。
如果自己设置了主键想插入 请直接明确调用insert方法。

**Comment by yangfuhai** [comment]
理解有问题，插入或更新时刚才当前实体类的值来判断的，而不是数据库的内容。

**Comment by chenxu8989** [comment]
## 这个问题我也碰到了, 以前我是用的spring data jpa, 它的save方法就是你说的这种逻辑 , 但是mybatis-flex这边的处理方式不同, 我想了下, 可以通过重载 BaseMapper 这个接口来解决这个问题

```java
/**
 * 重载 BaseMapper 接口的部分方法
 * @param <T>
 */
public interface CustomBaseMapper<T> extends BaseMapper<T> {

	@Override
	default int insertOrUpdate(T entity) {
		return insertOrUpdate(entity, false);
	}

	/**
	 * 插入或更新实体对象
	 *
	 * 该方法旨在处理实体对象的插入或更新操作，根据ignoreNulls参数决定是否忽略null值字段 当更新操作影响的行数小于等于0时，会尝试插入该实体对象
	 *
	 * @param entity      要插入或更新的实体对象
	 * @param ignoreNulls 是否忽略实体对象中的null值字段
	 * @return 返回受影响的行数
	 */
	@Override
	default int insertOrUpdate(T entity, boolean ignoreNulls) {
		// 尝试更新实体对象，ignoreNulls参数决定是否忽略null值字段
		int affectedNum = BaseMapper.super.insertOrUpdate(entity, ignoreNulls);
		// 如果更新操作未影响任何行，尝试插入实体对象
		if (affectedNum <= 0) {
			return BaseMapper.super.insert(entity);
		}
		// 返回更新操作影响的行数
		return affectedNum;
	}

	@Override
	default int insertOrUpdateSelective(T entity) {
		return insertOrUpdate(entity);
	}
}

```

## 然后让自己的 mapper 去继承这个自定义的 CustomBaseMapper 就行了

```java
@Mapper
public interface AccountMapper extends CustomBaseMapper<Account> {

}
```
