### ISSUE TITLE
使用自定义枚举typeHandler时无效

### ISSUE THREAD

**Issue by luo-zhan** [mybatis-flex/mybatis-flex#269]
使用自定义枚举TypeHander功能，配合mybatis-plus正常，配合flex无效，示例代码：
```java
@Configuration
public class DictMybatisConfiguration implements ApplicationContextAware {

    @Override
    public void setApplicationContext(ApplicationContext applicationContext) {
        SqlSessionFactory sqlSessionFactory = applicationContext.getBean(SqlSessionFactory.class);
        TypeHandlerRegistry typeHandlerRegistry = sqlSessionFactory.getConfiguration().getTypeHandlerRegistry();
        typeHandlerRegistry.setDefaultEnumTypeHandler(DictTypeHandler.class);
    }

}
```

跟踪源码，发现是扫描实体类时，就自动初始化了属性的ColumnInfo，然后设置了枚举属性的`buildTypeHandler`为配置里的`defaultEnumTypeHandler`，但此时还没有执行到上述代码，所以使用的还是默认的`CompositeEnumTypeHandler`。

上面自定义的`DictTypeHandler`是项目[EasyEnum](https://github.com/luo-zhan/EasyEnum)里的mybatis插件，为了适配性，只引入了mybatis，不方便使用flex的配置，有没有什么办法可以兼容flex，或者flex能延迟加载buildTypeHandler。

ps.一般项目里不太适用框架的枚举注解方式，因为枚举一般放在common包或api包下，不希望引入orm框架依赖，所以使用枚举接口+自定义枚举TypeHandler比较合适。

**Comment by yangfuhai** [comment]
下个版本支持
