### ISSUE TITLE
请问有类似MyBatis-Plus的LambdaWrapper的吗？

### ISSUE THREAD

**Issue by JSpringYC** [mybatis-flex/mybatis-flex#27]
感觉这个还挺好用的

**Comment by 203579397** [comment]
加一

**Comment by luo-zhan** [comment]
> 感觉这个还挺好用的

flex和plus就是两种实现思路啊，已经有静态常量了，还要lambda干嘛，不是比lambda性能更好且易读吗

**Comment by semmywong** [comment]
+1

**Comment by Suomm** [comment]
看看教程吧，【MyBatis-Flex 视频教程 - 14 QueryWrapper 的介绍】 https://www.bilibili.com/video/BV1Mm4y177nq/?share_source=copy_web&vd_source=6986f9a4ec12e628ff34aa4316d740fe

**Comment by aohanhongzhi** [comment]
> > 感觉这个还挺好用的
> 
> flex和plus就是两种实现思路啊，已经有静态常量了，还要lambda干嘛，不是比lambda性能更好且易读吗

![image](https://github.com/mybatis-flex/mybatis-flex/assets/37319319/b174f374-d5a3-4315-987a-82866a3c2ea6)

这个静态常量是自动生成的吗？

**Comment by Suomm** [comment]
> > > 感觉这个还挺好用的
> > 
> > 
> > flex和plus就是两种实现思路啊，已经有静态常量了，还要lambda干嘛，不是比lambda性能更好且易读吗
> 
> ![image](https://user-images.githubusercontent.com/37319319/254465299-b174f374-d5a3-4315-987a-82866a3c2ea6.png)
> 
> 这个静态常量是自动生成的吗？

看看教程吧

【MyBatis-Flex 视频教程 - 04基于 SpringBoot 的快速开始】 [https://www.bilibili.com/video/BV1yW4y1Z74j/?share_source=copy_web&vd_source=6986f9a4ec12e628ff34aa4316d740fe](https://gitee.com/link?target=https%3A%2F%2Fwww.bilibili.com%2Fvideo%2FBV1yW4y1Z74j%2F%3Fshare_source%3Dcopy_web%26vd_source%3D6986f9a4ec12e628ff34aa4316d740fe)

【MyBatis-Flex 视频教程 - 05自动生成类的介绍】 [https://www.bilibili.com/video/BV1XF411R7pQ/?share_source=copy_web&vd_source=6986f9a4ec12e628ff34aa4316d740fe](https://gitee.com/link?target=https%3A%2F%2Fwww.bilibili.com%2Fvideo%2FBV1XF411R7pQ%2F%3Fshare_source%3Dcopy_web%26vd_source%3D6986f9a4ec12e628ff34aa4316d740fe)

**Comment by yangfuhai** [comment]
lambda 是支持的，请参考文档：https://mybatis-flex.com/zh/base/querywrapper.html#lambda-%E6%89%A9%E5%B1%95

**Comment by luo-zhan** [comment]
> lambda 是支持的，请参考文档：https://mybatis-flex.com/zh/base/querywrapper.html#lambda-%E6%89%A9%E5%B1%95

真心觉得没必要实现lambda方式，功能不是越多越好，好的设计应该是懂得做减法，有静态常量还提供lambda方式，只会带来使用上的混乱，不利于维护
