### ISSUE TITLE
整合 solon+postgresql的一些问题

### ISSUE THREAD

**Issue by ppengyi** [mybatis-flex/mybatis-flex#28]
1. Column 自定义 typeHandler 会出现 Cannot invoke "org.apache.ibatis.session.Configuration.getTypeHandlerRegistry()" because "configuration" is null 的问题
![image](https://github.com/mybatis-flex/mybatis-flex/assets/34240593/d2ba5cf5-a3d4-4b91-b781-4d619d627f30)
我看了solon-plugin 没有发现设置defaultConfig的地方，我修改了插件，
![image](https://github.com/mybatis-flex/mybatis-flex/assets/34240593/7ffb652c-e958-4ff2-a281-1fc1714f78ef)
可以正常运行
2. 我定义了逻辑删除的字段为bool类型，正常查询的时候没有问题，如果通过主键查询会出现sql错误,我查找了一下是方言问题
![image](https://github.com/mybatis-flex/mybatis-flex/assets/34240593/705fb30e-fbc6-44eb-9c07-1a92e68d609b)
格式化出来是 "xxxx" 这个在postgresql是无法执行的

**Comment by yangfuhai** [comment]
第二点已经优化 push 代码，针对第一点是否来个 pr？

**Comment by noear** [comment]
关于 defaultConfig 默认配置，是有设置的。

```java
  protected void initAfter(BeanWrap dsWrap) {
      globalConfig.setSqlSessionFactory(getFactory());

      if (dsWrap.typed()) {
          FlexGlobalConfig.setDefaultConfig(globalConfig);
      }
  }
```

但在使用时要注意2点：

1. 使用的时机，如果插件初始化未完成。你是拿不到的

最好通过注入的方式获取 “@Db("db1") FlexConfiguration cfg； @Db("db1") FlexGlobalConfig globalConfig”。然后通过 solon bean 生命周期的接口 InitializingBean 去处理它：http://solon.noear.org/article/448


2. 需要在创建 datasource bean 时，申请为 typed （即增加按类型注册）。比如这样：

```java
//配置数据源
@Configuration
public class Config {
    //此下的 db1 与 mybatis.db1 将对应在起来 //可以用 @Db("db1") 注入mapper
    //typed=true，表示默认数据源。@Db 可不带名字注入 
    @Bean(value = "db1", typed = true)
    public DataSource db1(@Inject("${demo.db1}") HikariDataSource ds) {
        return ds;
    }
    
    //调整 db1 的配置（如：增加插件）// (配置可以解决的，不需要这块代码)
    //@Bean
    //public void db1_cfg(@Db("db1") FlexConfiguration cfg,
    //                    @Db("db1") FlexGlobalConfig globalConfig) {

    //    cfg.setCacheEnabled(false);

    //}
}
```

**Comment by noear** [comment]
关于 "mybatis-flex-solon-plugin" 的使用，可以再看下此文：

https://solon.noear.org/article/489

**Comment by yangfuhai** [comment]
相关问题在 flex 新版本已经解决，同时 solon 作者已经给出解答，先关闭，后续有问题再开启。
