### ISSUE TITLE
processor 编译器在maven 子项目中无法获取配置文件

### ISSUE THREAD

**Issue by imaxun** [mybatis-flex/mybatis-flex#29]
mybatis-flex.properties配置文件如下：
processor.tablesNameStyle=LowerCamelCase
processor.entity.ignoreSuffixes=Entity

**Comment by imaxun** [comment]
示例截图：
![image](https://github.com/mybatis-flex/mybatis-flex/assets/29112991/ab050d75-fe61-4b29-b2c5-bc337bc0591c)

**Comment by imaxun** [comment]
这个不打算修复么

**Comment by jackson-som** [comment]
![image](https://github.com/mybatis-flex/mybatis-flex/assets/50586111/54cfffab-6160-44f4-a519-2cea5768014e)

尝试把 LowerCamelCase 变成 lowerCamelCase
我的是没这问题

**Comment by yangfuhai** [comment]
新版本已修复，请升级到最新版本。
