### ISSUE TITLE
1.8.2版本的事务不生效

### ISSUE THREAD

**Issue by EddyChina** [mybatis-flex/mybatis-flex#295]
springboot 3.2.2
flex: 1.8.2
db: aws rds latest version

方法使用@Transactional注解，在方法内insert一条数据，然后接下来的代码报错，但数据并没有回滚。

顺便测了1.8.1也有问题。

1.8.0事务是生效的。  

pseudo code：
`
@Transactional
public void creatTenant(Tenant tenant) {
    tenantMapper.insert(tenant);

    // something wrong happens here, but data could be fetched from database
}
`

**Comment by yangfuhai** [comment]
@EddyChina  建议尝试 v1.8.4 看看
