### ISSUE TITLE
使用QueryWrapper的时候无法使用DISTINCT关键字

### ISSUE THREAD

**Issue by yztqdqsdlq** [mybatis-flex/mybatis-flex#298]

**Comment by yangfuhai** [comment]
参考文档：https://mybatis-flex.com/zh/base/querywrapper.html#select-function-sql-%E5%87%BD%E6%95%B0

**Comment by GabbyMrH** [comment]
确实不可以，官方文档没有示例，写在哪个位置都会报错。
