### ISSUE TITLE
字段别名为驼峰的时候映射不上吗

### ISSUE THREAD

**Issue by sauces88** [mybatis-flex/mybatis-flex#30]
![232](https://github.com/mybatis-flex/mybatis-flex/assets/54261755/5c5ef8d1-a4f0-4904-b120-ad73f87f517f)
![233](https://github.com/mybatis-flex/mybatis-flex/assets/54261755/8747c472-74f1-4fba-b35e-e3e2da1e0fe0)

**Comment by yangfuhai** [comment]
新版本已修复。
