### ISSUE TITLE
如何为子QueryWrapper起别名

### ISSUE THREAD

**Issue by 8OOOOOOOOD** [mybatis-flex/mybatis-flex#303]
如: 
![image](https://github.com/mybatis-flex/mybatis-flex/assets/55775562/1d56c7d1-4346-4a6e-92d3-f211d258e3c9)
这怎么写比较好

**Comment by Suomm** [comment]
写在 `leftJoin` 里面，例：`leftJoin( .as() )`

**Comment by Suomm** [comment]
下个版本把警告去掉吧，加警告是为了推荐新写法，注释有说明。
