### ISSUE TITLE
新特性

### ISSUE THREAD

**Issue by kenixFog** [mybatis-flex/mybatis-flex#320]
实际场景中，在使用queryWrapper时，where条件的值支持传递sql作为子查询~

**Comment by yangfuhai** [comment]
这个 feature 在很早的版本已支持，请查看官方文档的 QueryWrapper 章节。

**Comment by kenixFog** [comment]
应该是我没描述清楚，加入以下场景：
String select = "SELECT ID FROM T LEFT JOIN A ****** ";  // sql比较复杂，无法构建wrapper

QueryWrapper  wrapper = QueryWrapper.create()
    .select()
    .from(ACCOUNT)
    .where(ACCOUNT.ID.in ( select  ) );

这种方式是否支持？
