### ISSUE TITLE
1.9.0的FlexMapperProxy问题

### ISSUE THREAD

**Issue by yykxxx** [mybatis-flex/mybatis-flex#348]
版本: 1.9.0
问题: 从1.8.9升级至1.9.0后出现错误，细查之下发现是在多数据源下的数据源获取的问题。在1.8.9中使用的是实现InvocationHandler的MapperInvocationHandler类，在getConfigDataSourceKey方法中实现。在1.9.0中使用的是继承MybatisMapperProxy的FlexMapperProxy类，在getConfigDataSourceKey方法中实现。区别就是getConfigDataSourceKey中的实现，这也是问题所在。在1.9.0存在methodDsKeyCache的map，该map会缓存Method与数据源的绑定关系。在使用相同baseMapper方法的时候，现在map中查找，如果不存才需要通过UseDataSource注解，实体的dataSource去获取数据源。但是1.8.9不存在该问题因为1.8.9没有methodDsKeyCache。

![1717118333083](https://github.com/mybatis-flex/mybatis-flex/assets/19881187/2f01eb7e-eb38-4ea2-abac-6e705edf687b)
![1717118376962](https://github.com/mybatis-flex/mybatis-flex/assets/19881187/e57f70f2-9368-4c05-88d9-76384738c011)
![1717118636621](https://github.com/mybatis-flex/mybatis-flex/assets/19881187/abba5346-dcb0-4bf0-b29d-0614c8f5bb45)

**Comment by yangfuhai** [comment]
可以来个 pr

**Comment by yangfuhai** [comment]
fixed. 下个版本发布
