### ISSUE TITLE
请问, 有没有QueryWrapper生成sql语句的方法, 不直接调用sql查询, 只想利用QueryWrapper生成一个sql语句

### ISSUE THREAD

**Issue by 15637942788** [mybatis-flex/mybatis-flex#356]
我想使用 QueryWrapper 生成一个sql语句. 使用方法: String sqlSelect = queryWrapper.getSqlSelect(); 打印出来是 null . 
请问有没有方法支持生成sql呢? 
或者请问有没有办法支持 reactive 响应式请求?

**Comment by AbbadoLambily** [comment]
.toSQL();

**Comment by Suomm** [comment]
queryWrapper.toSQL();
