### ISSUE TITLE
mybatis-flex.properties配置项移动到application.properties

### ISSUE THREAD

**Issue by shaoerkuai** [mybatis-flex/mybatis-flex#36]
能否将mybatis-flex.properties挪动到application.properties中？新建mybatis-flex.properties感觉比较麻烦一些

**Comment by 203579397** [comment]
加一

**Comment by jackson-som** [comment]
没错，加一

**Comment by Suomm** [comment]
这两个文件是不一样的！

mybatis-flex.properties 是用来配置 APT 生成的，和 spring boot 没有任何关系。
