### ISSUE TITLE
oracle数据库使用Db.updateBatchById批量更新

### ISSUE THREAD

**Issue by kaibo-li** [mybatis-flex/mybatis-flex#366]
oracle数据库不支持 update tab set xxx; update tab set xxx; 
![EC825A99E3B90A826FF3BF2D858850A9](https://github.com/mybatis-flex/mybatis-flex/assets/34088314/95b09e15-8c93-47e5-95b7-1b8fc0dfa0b8)

**Comment by Suomm** [comment]
数据库不支持，我们也没有办法呢。
