### ISSUE TITLE
save方法报错

### ISSUE THREAD

**Issue by xjcxjcxjc** [mybatis-flex/mybatis-flex#368]
同一个实体类的两个不同新增业务，即两条插入sql不同会在重新调用第一条sql时报错

**Comment by xjcxjcxjc** [comment]
刚开始调的save，后面调的saveOrUpdate，然后再调save接口就报错了

**Comment by yangfuhai** [comment]
这个问题是第一次反馈，麻烦给出完整的错误信息。

**Comment by xjcxjcxjc** [comment]
没事了，是数据库连接器版本过高
