### ISSUE TITLE
[Question] APT指定生成类位置

### ISSUE THREAD

**Issue by fangzhengjin** [mybatis-flex/mybatis-flex#385]
@yangfuhai 想问一下这个指定生成类的包名出现了什么问题吗？更新忽然发现不能启动, 原来是代码回滚了
302277609dc67719af927c53dc98148b18471304
aa85c7663557bd26fc5434d9e4a59fac786f67d7

**Comment by yangfuhai** [comment]
之前的这个 pr 导致文档里的很多配置不生效了，影响很大，群里有非常多人反馈了这个问题，智能暂时回退到之前的版本了，之前的这个 pr 应该是测试不到位导致的。

**Comment by fangzhengjin** [comment]
> 之前的这个 pr 导致文档里的很多配置不生效了，影响很大，群里有非常多人反馈了这个问题，智能暂时回退到之前的版本了，之前的这个 pr 应该是测试不到位导致的。

啊，是群里反馈的，我说怎么两边的issue都搜不到相关信息😂

有没有具体哪些问题呀，我来调整下，我这边用着都是正常的

**Comment by yangfuhai** [comment]
> > 之前的这个 pr 导致文档里的很多配置不生效了，影响很大，群里有非常多人反馈了这个问题，智能暂时回退到之前的版本了，之前的这个 pr 应该是测试不到位导致的。
> 
> 啊，是群里反馈的，我说怎么两边的issue都搜不到相关信息😂
> 
> 有没有具体哪些问题呀，我来调整下，我这边用着都是正常的

可以加我微信 fuh99888 沟通一下。
