### ISSUE TITLE
关联查询的一些疑问

### ISSUE THREAD

**Issue by zhengchalei** [mybatis-flex/mybatis-flex#386]
假设有一个RBAC模型, 
我需要从用户 -> 角色 -> 权限

我有时候需要查询 角色, 有些情况 需要查询到下面权限,  或者更深层次的级联, 这种场景是怎么做的

**Comment by yangfuhai** [comment]
默认情况下只查询 3 个层级，具体文档可以参考 https://mybatis-flex.com/zh/base/relations-query.html#%E7%88%B6%E5%AD%90%E5%85%B3%E7%B3%BB%E6%9F%A5%E8%AF%A2
