### ISSUE TITLE
多数据源的配置如果有上万个数据源怎么办？

### ISSUE THREAD

**Issue by dododcdc** [mybatis-flex/mybatis-flex#404]
用户在界面可以自己写sql，写完后他会选择一个数据源执行这个sql

**Comment by Suomm** [comment]
动态处理多数据源：https://mybatis-flex.com/zh/core/multi-datasource.html#%E5%8A%A8%E6%80%81%E6%B7%BB%E5%8A%A0%E6%96%B0%E7%9A%84%E6%95%B0%E6%8D%AE%E6%BA%90
