### ISSUE TITLE
如果我的数据库表名和字段和JAVA对象一样有配置的方法吗

### ISSUE THREAD

**Issue by qqcbqqkcel** [mybatis-flex/mybatis-flex#43]
我看处理@Table源码中如果不写表格首字母会小写

![image](https://github.com/mybatis-flex/mybatis-flex/assets/4516585/a3eeacaf-1b35-4de8-bf8f-d89e5daa58a4)

**Comment by yangfuhai** [comment]
新版本已添加 配置 processor.tablesDefSuffix 支持，用于解决冲突的问题。
