### ISSUE TITLE
代码生成器问题

### ISSUE THREAD

**Issue by z2z2qp** [mybatis-flex/mybatis-flex#46]
如果我不需要生成Service接口注释掉如图，
![S6%IIHGB4_RH0JG 561O~PI](https://github.com/mybatis-flex/mybatis-flex/assets/10736433/242d7e53-c440-4df0-beed-a7a6e422ba60)

会导致后续ServiceImpl以及Controller 找不到 Service类；
在极端点，作为测试去测试，如果我没开启Entity的生成，那全部都飘红了

**Comment by Suomm** [comment]
这个不能强制检测是否引用类已经生成，`enableXxx()` 应对的情况是，如果有已经生成好的了，就不用生成了，没有生成的在调用方法生成。

**Comment by Suomm** [comment]
你把它注掉，就意味着你不要生成它，但是不生成还不行，那为什么要注掉呢？忘掉？

**Comment by z2z2qp** [comment]
https://github.com/mybatis-flex/mybatis-flex/issues/46#issuecomment-1581806264
因为我们约定，如果当前只有一种service实现，不需要IService接口，写一个service的方法，文件跳来跳去，接口里面写一遍，实现写一遍很繁琐；

所以我希望生成Service就行了，不需要IService

**Comment by Suomm** [comment]
也就是说，生成的 Service 和 ServiceImpl 不继承 IService 是吧？

```java
public interface UserService {

} 

public class UserServiceImpl implements UserService {

    @Autowired
    private UserMapper userMapper;

}
```

像这个例子一样？我的理解没错吧。

**Comment by z2z2qp** [comment]
不是   我只需要生成这个类就行了
```java
@Service
public class UserService extends ServiceImpl {
    @Autowired
    private UserMapper userMapper;
}
```

**Comment by Suomm** [comment]
> 不是 我只需要生成这个类就行了
> 
> ```java
> @Service
> public class UserService extends ServiceImpl {
>     @Autowired
>     private UserMapper userMapper;
> }
> ```

通过自定义模板实现：

```text
#set(mapperClass = table.buildMapperClassName())
package #(packageConfig.serviceImplPackage);

import #(serviceImplConfig.buildSuperClassImport());
import #(packageConfig.entityPackage).#(table.buildEntityClassName());
import #(packageConfig.mapperPackage).#(table.buildMapperClassName());
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

/**
 * #(table.getComment()) 服务层实现。
 *
 * @author #(javadocConfig.getAuthor())
 * @since #(javadocConfig.getSince())
 */
@Service
public class #(table.buildServiceImplClassName()) extends #(serviceImplConfig.buildSuperClassName())<#(mapperClass), #(table.buildEntityClassName())> {

    @Autowired
    private #(mapperClass) #(firstCharToLowerCase(mapperClass));

}
```

然后将模板路径设置到 TemplateConfig，类路径以 `/` 开头，硬盘的话以盘符开头。

```java
globalConfig.getTemplateConfig()
                .setServiceImpl("......")
```

**Comment by Suomm** [comment]
文件后缀名是 `.tpl`，如果不想有 `Impl` 后缀，可以将 ServiceImpl 的后缀设为 `"Service"`。

**Comment by z2z2qp** [comment]
👌👌

**Comment by nitenzhao** [comment]
希望有一种配置能直接生成service层的实现类，多数情况下是用不到service接口的
