### ISSUE TITLE
MybatisFlexAutoConfiguration疑问

### ISSUE THREAD

**Issue by daihy8759** [mybatis-flex/mybatis-flex#47]
mybatis默认会创建SqlSessionFactory吧，这个bean是不是没办法初始化
![图片](https://github.com/mybatis-flex/mybatis-flex/assets/6057326/da2169ce-4037-4e8a-b29e-baddd1e290a6)

带来的问题就是一些配置没办法生效，例如configurationCustomizers，数据库类型读取等等

**Comment by Suomm** [comment]
自定义 SqlSessionFactoryBean 参阅：
https://github.com/mybatis-flex/mybatis-flex/blob/main/mybatis-flex-spring-boot-starter/src/main/java/com/mybatisflex/spring/boot/SqlSessionFactoryBeanCustomizer.java

**Comment by yangfuhai** [comment]
新版本验证已无此问题。
