### ISSUE TITLE
 object is not an instance of declaring class

### ISSUE THREAD

**Issue by hadoop835** [mybatis-flex/mybatis-flex#50]
![Dingtalk_20230607183327](https://github.com/mybatis-flex/mybatis-flex/assets/8055054/95c31da1-55aa-4d1d-956d-65aec45713b7)

**Comment by yangfuhai** [comment]
麻烦给出具体的使用代码

**Comment by hadoop835** [comment]
### 业务模块包
[spring-boot-ark-biz.zip](https://github.com/mybatis-flex/mybatis-flex/files/11684783/spring-boot-ark-biz.zip)
### 基座运行业务逻辑jar
    idea 启动参数 -Dsofa.ark.embed.enable=true -Dsofa.ark.embed.static.biz.enable=true
 [sofa-ark-spring-guides.zip](https://github.com/mybatis-flex/mybatis-flex/files/11684797/sofa-ark-spring-guides.zip)
    通过postmain访问 POST http://127.0.0.1:8080/biz/save

**Comment by yangfuhai** [comment]
@hadoop835  感谢 push 修复代码，这个 issues 先关闭了。
