### ISSUE TITLE
是否支持dubbo Wrapper 传递

### ISSUE THREAD

**Issue by GMY-life** [mybatis-flex/mybatis-flex#58]

**Comment by yangfuhai** [comment]
QueryWrapper 是支持序列化的，因此理论支持任何 RPC 传输。但是，每个 RPC 框架所用到的序列化方案有所不同，这个具体还需要测试和验证。记得 Dubbo 默认的序列化方案是 hessian，您可以验证后告知我们。

更多关于 QueryWrapper 序列化的文档： https://mybatis-flex.com/zh/base/querywrapper.html#querywrapper-%E5%BA%8F%E5%88%97%E5%8C%96

**Comment by GMY-life** [comment]
Dubbo fastjson2序列化方案验证成功
