### ISSUE TITLE
@EnumValue 注解功能缺陷

### ISSUE THREAD

**Issue by GMY-i** [mybatis-flex/mybatis-flex#60]
```
public enum UserType {
    ADMIN,
    USER,
    MERCHANT,
    ;
}

```

如果一个enum没有自定义字段的情况，如何使用@EnumValue，或者可以提供一个接口实现？

[文档链接](https://mybatis-flex.com/zh/core/enum-property.html)

**Comment by yangfuhai** [comment]
如果没用字段，直接使用就可以的，数据库存入的是其 name。

**Comment by yangfuhai** [comment]
新增版本验证没有问题。
