### ISSUE TITLE
很棒的工作，有没有可能支持更多的回调（类似ActiveRecord)。

### ISSUE THREAD

**Issue by hjleochen** [mybatis-flex/mybatis-flex#70]
参考 ActiveRecord：https://guides.rubyonrails.org/active_record_callbacks.html

特别是after_update， 这种可对比数据内容变更的功能。
```ruby
  u.tel = '13688888888'
  u.name = 'Test'
  u.changes
```

```ruby
{"name"=>["你好", "Test"], "tel"=>["136111111", "13688888888"]}
```

**Comment by yangfuhai** [comment]
v1.5.3 版本已支持，文档：https://mybatis-flex.com/zh/base/active-record.html
