### ISSUE TITLE
selectXXXByQueryAs方法结果映射错误

### ISSUE THREAD

**Issue by fskanokano** [mybatis-flex/mybatis-flex#71]
当两个表中有同名的字段时，使用selectXXXByQueryAs方法有一方会映射失败
比如

public class User implements Serializable {

    @Id(value = "id", keyType = KeyType.Auto)
    private Integer id;

    @Column("name")
    private String name;

    @Column("age")
    private Integer age;

    private List<Book> books;

}

public class Book implements Serializable {

    @Id(value = "id", keyType = KeyType.Auto)
    private Integer id;

    @Column("name")
    private String name;

    @Column("user_id")
    private Integer userId;

}

        QueryWrapper queryWrapper = QueryWrapper
                .create()
                .select(USER.ALL_COLUMNS,BOOK.ALL_COLUMNS)
                .from(USER).as("u")
                .join(BOOK).as("b")
                .on(USER.ID.eq(BOOK.USER_ID))
                .where(USER.NAME.eq("sui"));
        User user = userMapper.selectOneByQueryAs(queryWrapper, User.class);

这段代码运行结果中，user对象映射的books列表中，id 和 name这两个字段会映射失败，因为同名了，使用selectWithRelations可以正常映射，但是这个方法会进行二次查询，对性能会有影响，有什么解决办法吗

**Comment by yangfuhai** [comment]
当前使用的是哪个版本？另外这个执行的 sql 是什么样的呢？

**Comment by fskanokano** [comment]
> 当前使用的是哪个版本？另外这个执行的 sql 是什么样的呢？

版本是 1.4.9
下面是执行的sql以及输出的结果，可以看到books中的book对象 id 和 name两个与 user 表中有同名的字段映射失败了，但是  userId 字段正常映射出来了
![image](https://github.com/mybatis-flex/mybatis-flex/assets/66066009/21c275f9-8b18-4a1e-9ec2-19084da8e100)

**Comment by Suomm** [comment]
select(USER.DEFAYLT_COLUMNS,BOOK.DEFAULT_COLUMNS)

**Comment by fskanokano** [comment]
> select(USER.DEFAULT_COLUMNS,BOOK.DEFAULT_COLUMNS)

改成 DEFAULT_COLUMNS 之后 name 字段可以正常映射了，但id还是不行
![image](https://github.com/mybatis-flex/mybatis-flex/assets/66066009/86b96e4a-3afa-43e1-a17b-b4d4e7079fbe)

**Comment by yangfuhai** [comment]
> > select(USER.DEFAULT_COLUMNS,BOOK.DEFAULT_COLUMNS)
> 
> 改成 DEFAULT_COLUMNS 之后 name 字段可以正常映射了，但id还是不行 ![image](https://user-images.githubusercontent.com/66066009/253837563-86b96e4a-3afa-43e1-a17b-b4d4e7079fbe.png)

@fskanokano 这个添加群后，可以远程看下。
