### ISSUE TITLE
多数据源的负载均衡策略是否支持

### ISSUE THREAD

**Issue by ahgaoyong** [mybatis-flex/mybatis-flex#76]
隔壁的[dynamic-datasource-spring-boot-starter](https://github.com/baomidou/dynamic-datasource-spring-boot-starter)支持配置多数据源的负载均衡

比如配置的数据源名称分别是ds_1,ds_2,ds_3,....
在使用的时候通过ds这个数据源的关键词就可以自动实现自动负载均衡到多个以ds_N格式的数据源
应用于多只读库的场景,大量的查询一台只读数据库的服务器扛不住的场景下

**Comment by yangfuhai** [comment]
已提交代码，下个版本 v1.5.4 会支持这个功能。文档：https://mybatis-flex.com/zh/core/multi-datasource.html#%E5%A4%9A%E6%95%B0%E6%8D%AE%E6%BA%90%E8%B4%9F%E8%BD%BD%E5%9D%87%E8%A1%A1
