### ISSUE TITLE
accountMapper.paginateAs报泛型错误

### ISSUE THREAD

**Issue by liu-xinhui** [mybatis-flex/mybatis-flex#80]
<img width="790" alt="image" src="https://github.com/mybatis-flex/mybatis-flex/assets/7698511/5881a43e-cce2-4d23-b582-c8ede1759a78">

参数和返回值泛型定义的都没问题，任然有警告

**Comment by loong0306** [comment]
> <img alt="image" width="790" src="https://user-images.githubusercontent.com/7698511/255594902-5881a43e-cce2-4d23-b582-c8ede1759a78.png">
> 参数和返回值泛型定义的都没问题，任然有警告

1.5.5未复现

**Comment by loong0306** [comment]
但此处发现一个bug，在未设置别名的时候，此处会默认补充别名，但逻辑符号异常
![image](https://github.com/mybatis-flex/mybatis-flex/assets/12693644/aa715610-c037-4fac-a377-06127bf5081b)
![image](https://github.com/mybatis-flex/mybatis-flex/assets/12693644/ec4036d1-45a6-40ca-a570-55d3d1b0959d)

**Comment by loong0306** [comment]
> 但此处发现一个bug，在未设置别名的时候，此处会默认补充别名，但逻辑符号异常 ![image](https://user-images.githubusercontent.com/12693644/257996238-aa715610-c037-4fac-a377-06127bf5081b.png) ![image](https://user-images.githubusercontent.com/12693644/257996294-ec4036d1-45a6-40ca-a570-55d3d1b0959d.png)

com.mybatisflex.core.dialect.implCommonsDialectImpl (line352)

**Comment by loong0306** [comment]
CommonsDialectImpl不清楚这块的设计逻辑是什么，无法直接提交PR，请直接根据test进行参考即可。

**Comment by yangfuhai** [comment]
逻辑符号异常值得是？是否有什么日志？

**Comment by yangfuhai** [comment]
> CommonsDialectImpl不清楚这块的设计逻辑是什么，无法直接提交PR，请直接根据test进行参考即可。 @yangfuhai

这部分的设计逻辑，参考文档：https://mybatis-flex.com/zh/base/auto-mapping.html#%E9%87%8D%E5%90%8D%E6%98%A0%E5%B0%84  用于解决映射重命的问题。

**Comment by loong0306** [comment]
> > CommonsDialectImpl不清楚这块的设计逻辑是什么，无法直接提交PR，请直接根据test进行参考即可。 @yangfuhai
> 
> 这部分的设计逻辑，参考文档：https://mybatis-flex.com/zh/base/auto-mapping.html#%E9%87%8D%E5%90%8D%E6%98%A0%E5%B0%84 用于解决映射重命的问题。

我明白您这块的设计模式了，为了解决多表联查字段自动映射通过ColumnAlias注解的形式去处理$映射。
但可能存在的问题是，多表联查后，只返回需要的类型，但是因不规范选用了其他的mapper，所以会导致返回结果的字段没有映射正确。
![image](https://github.com/mybatis-flex/mybatis-flex/assets/12693644/add8c410-3d78-4f86-be9b-ee2e4155350e)

**Comment by yangfuhai** [comment]
新版本验证没有问题。
