### ISSUE TITLE
仅生成ServiceImpl，不生成接口时，会报错

### ISSUE THREAD

**Issue by liu-xinhui** [mybatis-flex/mybatis-flex#83]
希望仅生成ServiceImpl时，不实现接口。
很多公司service层不需要接口，只有用rpc时接口才有用吧。我们用feign，用不到接口，写了反而增加工作量。

<img width="1090" alt="image" src="https://github.com/mybatis-flex/mybatis-flex/assets/7698511/d35759db-6753-443c-a80a-037dde33599d">

**Comment by liu-xinhui** [comment]
<img width="1008" alt="image" src="https://github.com/mybatis-flex/mybatis-flex/assets/7698511/14ea8916-366d-4a5b-9aa2-2796f7358638">
<img width="666" alt="image" src="https://github.com/mybatis-flex/mybatis-flex/assets/7698511/9b1c255e-d605-4e51-aebc-9b2207c7007a">

自定义生成器模板，官网文档不正确。文档中有generateEntity方法，实际代码中没有。

**Comment by yangfuhai** [comment]
文档已更新。

**Comment by nitenzhao** [comment]
希望有一种配置能直接生成service层的实现类，多数情况下是用不到service接口的
